// everyday-market/everyday-market-react/src/components/market/CategoryMenuItem/CategoryMenuItem.js
import React from 'react';
import './CategoryMenuItem.css';

function getItemClassNames(checked) {
  return 'menu-item-container' + (checked ? ' menu-item-selected' : '');
}

const CategoryMenuItem = (props) => (
  <div
    onClick={() => props.onSelected(props.categoryName)}
    className={getItemClassNames(props.checked)}
  >
    <span>{props.categoryName}</span>
  </div>
);

export default CategoryMenuItem;

// everyday-market/everyday-market-ng/src/app/modules/market/category-menu-item/category-menu-item.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-category-menu-item',
  templateUrl: './category-menu-item.component.html',
  styleUrls: ['./category-menu-item.component.css']
})
export class CategoryMenuItemComponent {
  @Input() categoryName: string;
  @Input() checked = false;
  @Output() selected = new EventEmitter<string>();

  onSelected() {
    this.selected.emit(this.categoryName);
  }
}

<div class="container" (click)="onSelected()" [class.selected]="checked">
  <span>{{ categoryName }}</span>
</div>
