// everyday-market/everyday-market-react/src/components/market/CategoryMenu/CategoryMenu.js
import React from 'react';
import './CategoryMenu.css';
import {CategoryMenuItem} from '../';

class CategoryMenu extends React.Component {
  state = {
    selectedCategoryName: null,
  };

  onCategorySelected = (categoryName) => {
    const cat = this.props.categories.find(c => c.name === categoryName);
    
    this.props.onCategoryChanged(cat);

    this.setState({selectedCategoryName: cat.name});
  };

  render() {
    return (
      <ul id="cat-menu">
        {this.props.categories.map(c => (
          <li key={c.name}>
            <CategoryMenuItem
              categoryName={c.name}
              checked={c.name === this.state.selectedCategoryName}
              onSelected={this.onCategorySelected}
            />
          </li>
        ))}
      </ul>
    );
  }
} 

export default CategoryMenu;

// everyday-market/everyday-market-vue/src/components/market/CategoryMenu.vue
<template>
  <ul>
    <li v-for="c in categories" :key="c.name">
      <CategoryMenuItem 
        :categoryName="c.name"
        :checked="c.name === selectedCategoryName"
        @selected="onCategorySelected"
      >
      </CategoryMenuItem >
    </li>
  </ul>
</template>

<script>
import CategoryMenuItem from './CategoryMenuItemFunctional.vue';

export default {
  name: 'CategoryMenu',
  components: {
    CategoryMenuItem,
  },
  props: {
    categories: Array,
  },
  data: () => ({
    selectedCategoryName: String,
  }),
  methods: {
    onCategorySelected: function(categoryName) {
      const cat = this.categories.find(c => c.name === categoryName);
      this.selectedCategoryName = cat.name;
      this.$emit('category-changed', cat);
    },
  },
}
</script>

<style scoped>
ul, li {
  list-style: none;
  padding: 0;
  margin: 0;
  display: inline;
}
</style>
