// everyday-market/everyday-market-react/src/components/market/ProductCard/ProductCard.js
import React from 'react';
import './ProductCard.css';

function primaryImageSrc(product) {
  return product && product.media && product.media.length > 0
    ? product.media[0].url
    : null;
}

const ProductCard = ({product}) => (
  <div className="item-card">
    <div className="item-card-content-container">
        <img className="item-card-content-container-img" alt="product"
             src={primaryImageSrc(product)} />
        <span className="item-card-content-container-title">{product.title}</span>
        <span className="item-card-content-container-text">{product.description}</span>
    </div>
  </div>
);

export default ProductCard;

// everyday-market/everyday-market-ng/src/app/modules/market/product-card/product-card.component.ts
import { Component, Input } from '@angular/core';
import { Product } from '../../../model';

@Component({
  selector: 'app-product-card',
  templateUrl: './product-card.component.html',
  styleUrls: ['./product-card.component.css']
})
export class ProductCardComponent {
  @Input() product: Product;

  get primaryImageSrc() {
    return this.product && this.product.media && this.product.media.length > 0
      ? this.product.media[0].url
      : null;
  }
}

<div class="item-card">
  <div class="item-card-content-container" [routerLink]="['/products', product.productId]">
      <img class="item-card-content-container-img" [src]="primaryImageSrc" />
      <span class="item-card-content-container-title">{{product.title}}</span>
      <span class="item-card-content-container-text">{{product.description}}</span>
  </div>
</div>
