// everyday-market/everyday-market-vue/src/components/common/Header.vue
<template>
  <header class="app-header app-bg">
    <div class="maxHeight flex flex-align-items--center">
      <img src="../../assets/logo.png" class="app-logo" />
      <span class="app-slogan">Shop 'till you Drop</span>
    </div>
  </header>
</template>

<script>
export default {
  name: 'Header',
}
</script>

<style scoped>
.app-header {
  height: 200px;
  border-bottom: 1px solid black;
}

.app-header::after {
  content: "";
  height: 200px;
  opacity: 0.5;
  background: url('../../assets/herobg.jpg');
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  z-index: -1;   
}

.app-logo {
  height: 80px;
  margin-left: 50px;
}

.app-slogan {
  font-family: 'Comic Sans MS', 'Comic Sans', cursive;
  font-weight: bold;
  margin-left: 5px;
}
</style>

// everyday-market/everyday-market-react/src/components/common/Header/Header.js
import React from 'react';
import './Header.css';
import headerLogo from '../../../assets/logo.png';

const Header = (props) => (
  <header className="app-header app-bg">
    <div className="maxHeight flex flex-align-items--center">
      <img src={headerLogo} className="app-logo" alt="logo" />
      <span className="app-slogan">Shop 'till you Drop</span>
    </div>
  </header>
);

export default Header;
