// everyday-market/everyday-market-react/src/components/market/CategoryMenu/CategoryMenu.js
import React from 'react';
import './CategoryMenu.css';
import {CategoryMenuItem} from '../';

class CategoryMenu extends React.Component {
  state = {
    selectedCategoryName: null,
  };

  onCategorySelected = (categoryName) => {
    const cat = this.props.categories.find(c => c.name === categoryName);
    
    this.props.onCategoryChanged(cat);

    this.setState({selectedCategoryName: cat.name});
  };

  render() {
    return (
      <ul id="cat-menu">
        {this.props.categories.map(c => (
          <li key={c.name}>
            <CategoryMenuItem
              categoryName={c.name}
              checked={c.name === this.state.selectedCategoryName}
              onSelected={this.onCategorySelected}
            />
          </li>
        ))}
      </ul>
    );
  }
} 

export default CategoryMenu;

// everyday-market/everyday-market-ng/src/app/modules/market/category-menu/category-menu.component.ts
import { Component, Input, EventEmitter, Output } from '@angular/core';
import { Category } from '../../../model';

@Component({
  selector: 'app-category-menu',
  templateUrl: './category-menu.component.html',
  styleUrls: ['./category-menu.component.css']
})
export class CategoryMenuComponent {
  @Input() categories: Category[];
  @Output() categoryChanged = new EventEmitter<Category>();
  selectedCategoryName: string;

  onCategorySelected(categoryName: string) {
    const cat = this.categories.find(c => c.name === categoryName);
    this.selectedCategoryName = cat.name;
    this.categoryChanged.emit(cat);
  }
}

<ul>
  <li *ngFor="let c of categories">
      <app-category-menu-item
        [categoryName]="c.name"
        [checked]="c.name === selectedCategoryName"
        (selected)="onCategorySelected($event)"
      >
      </app-category-menu-item>
  </li>
</ul>
